#!/usr/bin/bash

if [ ! -f "$1" ]; then
	echo No file: \""$1"\"
	exit
fi

cp "$1" /tmp/
name=$(basename "$1")

cat << EOF > /tmp/tmptikz.tex
\documentclass[11pt, oneside]{article} 
\usepackage{pgfplots} 
\usepackage{ae}
% and optionally (as of Pgfplots 1.3): 
\pgfplotsset{compat=newest} 
\\pgfplotsset{plot coordinates/math parser=false} 
\\newlength\\figureheight 
\\newlength\\figurewidth 
\\setlength\\figurewidth{0.9\\linewidth}
\\setlength\\figureheight{0.618\\linewidth}
\\pagestyle{empty}
\\begin{document} 
\\begin{figure}
	\\centering
	\\input{$name} 
\\end{figure}
\\end{document} 
EOF

oldpath=$(pwd)
cd /tmp
pdflatex -interaction=batchmode tmptikz > /dev/null
# pdflatex  tmptikz
pdfcrop tmptikz.pdf
pdf2pdf tmptikz-crop.pdf tmptikz-trim.pdf

# dvips tmptikz -q
# eps2eps -dNOCACHE tmptikz.ps tmptikz.eps
# epstopdf tmptikz.eps

# rm tmptikz.tex
# rm tmptikz.dvi
# rm tmptikz.ps
# rm tmptikz.eps
# rm "$name"

cd $oldpath
mv /tmp/tmptikz-trim.pdf $(dirname $1)/${name%.*}.pdf



